// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {claudecode} from '../models';
import {cursor} from '../models';
import {agent} from '../models';

export function AddProject(arg1:main.Project):Promise<void>;

export function BrowseClaudeCodeProjects():Promise<Array<claudecode.ScannedProject>>;

export function BrowseCursorProjects():Promise<Array<cursor.ScannedProject>>;

export function BrowseWorkspaceStorages():Promise<Array<Record<string, string>>>;

export function EmitFileProcessed(arg1:string,arg2:string):Promise<void>;

export function EmitWatcherEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FindProject(arg1:string):Promise<string>;

export function GetDefaultOutputDir(arg1:string):Promise<string>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetWorkspaceStoragePath():Promise<string>;

export function HandleDeletedFile(arg1:string,arg2:string):Promise<void>;

export function HealContrailNames(arg1:string,arg2:string):Promise<number>;

export function ListChatFiles(arg1:string):Promise<Array<main.ChatFileInfo>>;

export function OnCursorDatabaseChanged():Promise<void>;

export function PreviewChatFile(arg1:string,arg2:string):Promise<string>;

export function ProcessAllSessions(arg1:string):Promise<number>;

export function ProcessChatSessions(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ProcessClaudeCodeSessions(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ProcessFileIfNeeded(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProcessModifiedSince(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ProcessSingleFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadExistingContrail(arg1:string,arg2:string):Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function SaveProjects(arg1:Array<main.Project>):Promise<void>;

export function SelectChatSessionsDir():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function UpdateProject(arg1:main.Project):Promise<void>;

export function ValidateOutputDir(arg1:string):Promise<string>;

export function WriteContrail(arg1:agent.ParsedSession,arg2:string):Promise<string>;
