// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ApplyAppUpdate(arg1) {
  return window['go']['main']['App']['ApplyAppUpdate'](arg1);
}

export function BrowseClaudeCodeProjects() {
  return window['go']['main']['App']['BrowseClaudeCodeProjects']();
}

export function BrowseCursorProjects() {
  return window['go']['main']['App']['BrowseCursorProjects']();
}

export function BrowseWorkspaceStorages() {
  return window['go']['main']['App']['BrowseWorkspaceStorages']();
}

export function CheckForAppUpdate() {
  return window['go']['main']['App']['CheckForAppUpdate']();
}

export function DetectIDEs() {
  return window['go']['main']['App']['DetectIDEs']();
}

export function EmitFileProcessed(arg1, arg2) {
  return window['go']['main']['App']['EmitFileProcessed'](arg1, arg2);
}

export function EmitWatcherEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmitWatcherEvent'](arg1, arg2, arg3);
}

export function FindProject(arg1) {
  return window['go']['main']['App']['FindProject'](arg1);
}

export function GetAnalyticsEnabled() {
  return window['go']['main']['App']['GetAnalyticsEnabled']();
}

export function GetDefaultOutputDir(arg1) {
  return window['go']['main']['App']['GetDefaultOutputDir'](arg1);
}

export function GetDirectoryOpener() {
  return window['go']['main']['App']['GetDirectoryOpener']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkspaceStoragePath() {
  return window['go']['main']['App']['GetWorkspaceStoragePath']();
}

export function HandleDeletedFile(arg1, arg2) {
  return window['go']['main']['App']['HandleDeletedFile'](arg1, arg2);
}

export function HealContrailNames(arg1, arg2) {
  return window['go']['main']['App']['HealContrailNames'](arg1, arg2);
}

export function IgnoreChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['IgnoreChat'](arg1, arg2, arg3);
}

export function IsChatIgnored(arg1, arg2) {
  return window['go']['main']['App']['IsChatIgnored'](arg1, arg2);
}

export function ListChatFiles(arg1) {
  return window['go']['main']['App']['ListChatFiles'](arg1);
}

export function OnCursorDatabaseChanged() {
  return window['go']['main']['App']['OnCursorDatabaseChanged']();
}

export function OpenDirectoryWith(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryWith'](arg1, arg2);
}

export function PreviewChatFile(arg1, arg2) {
  return window['go']['main']['App']['PreviewChatFile'](arg1, arg2);
}

export function ProcessAllSessions(arg1) {
  return window['go']['main']['App']['ProcessAllSessions'](arg1);
}

export function ProcessChatSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessChatSessions'](arg1, arg2, arg3);
}

export function ProcessClaudeCodeSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessClaudeCodeSessions'](arg1, arg2, arg3);
}

export function ProcessFileIfNeeded(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessFileIfNeeded'](arg1, arg2, arg3);
}

export function ProcessModifiedSince(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessModifiedSince'](arg1, arg2, arg3);
}

export function ProcessSingleFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessSingleFile'](arg1, arg2, arg3);
}

export function ReadExistingContrail(arg1, arg2) {
  return window['go']['main']['App']['ReadExistingContrail'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SaveProjects(arg1) {
  return window['go']['main']['App']['SaveProjects'](arg1);
}

export function SelectChatSessionsDir() {
  return window['go']['main']['App']['SelectChatSessionsDir']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SetAnalyticsEnabled(arg1) {
  return window['go']['main']['App']['SetAnalyticsEnabled'](arg1);
}

export function SetDirectoryOpener(arg1) {
  return window['go']['main']['App']['SetDirectoryOpener'](arg1);
}

export function UnignoreChat(arg1, arg2) {
  return window['go']['main']['App']['UnignoreChat'](arg1, arg2);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function ValidateOutputDir(arg1) {
  return window['go']['main']['App']['ValidateOutputDir'](arg1);
}

export function WriteContrail(arg1, arg2) {
  return window['go']['main']['App']['WriteContrail'](arg1, arg2);
}
